version: '3'

services:
  calculator-api:
    build:
      context: calculator-api
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: always

  calculator-front:
    build:
      context: calculator-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - calculator-api